import type { Product } from "../types";

interface PDFExportProps {
  products: Product[];
  type: "sell-sheet" | "line-sheet";
}

function generateSellSheet(products: Product[]): string {
  const heroProducts = products.filter((p) => p.hero);
  const allProducts = products;
  const items = heroProducts.length > 0 ? heroProducts : allProducts;

  return `
    <html>
    <head>
      <title>Marie AI — Product Sell Sheet</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600;700&family=DM+Sans:wght@400;500;600&display=swap');
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DM Sans', sans-serif; color: #1A1611; padding: 40px; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #C4973B; padding-bottom: 24px; }
        .header h1 { font-family: 'Cormorant Garamond', Georgia, serif; font-size: 32px; color: #1A1611; margin-bottom: 4px; }
        .header p { font-size: 12px; color: #666; letter-spacing: 0.1em; text-transform: uppercase; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
        .product { border: 1px solid #E0D5C0; border-radius: 8px; padding: 20px; }
        .product h3 { font-family: 'Cormorant Garamond', Georgia, serif; font-size: 18px; margin-bottom: 4px; }
        .product .meta { font-size: 11px; color: #888; text-transform: uppercase; letter-spacing: 0.06em; margin-bottom: 8px; }
        .product .desc { font-size: 13px; color: #444; line-height: 1.6; margin-bottom: 8px; }
        .product .price { font-size: 16px; font-weight: 700; color: #8B6914; }
        .product .sku { font-size: 10px; color: #999; margin-top: 4px; }
        .footer { text-align: center; margin-top: 40px; padding-top: 16px; border-top: 1px solid #E0D5C0; font-size: 10px; color: #999; }
        .hero-badge { display: inline-block; background: #C4973B; color: white; font-size: 9px; padding: 2px 8px; border-radius: 10px; text-transform: uppercase; letter-spacing: 0.08em; font-weight: 600; margin-left: 8px; }
        @media print { body { padding: 20px; } .grid { gap: 16px; } }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Product Sell Sheet</h1>
        <p>Beauty Industry Collection · ${new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}</p>
      </div>
      <div class="grid">
        ${items.map((p) => `
          <div class="product">
            <h3>${p.name}${p.hero ? '<span class="hero-badge">Hero</span>' : ""}</h3>
            <div class="meta">${p.category} · ${p.sku}</div>
            <div class="desc">${p.description}</div>
            <div class="price">${p.price}</div>
          </div>
        `).join("")}
      </div>
      <div class="footer">
        Generated by Marie AI · ${new Date().toLocaleDateString()} · Confidential
      </div>
    </body>
    </html>
  `;
}

function generateLineSheet(products: Product[]): string {
  return `
    <html>
    <head>
      <title>Marie AI — Line Sheet</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600;700&family=DM+Sans:wght@400;500;600&display=swap');
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DM Sans', sans-serif; color: #1A1611; padding: 40px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #C4973B; padding-bottom: 20px; }
        .header h1 { font-family: 'Cormorant Garamond', Georgia, serif; font-size: 28px; margin-bottom: 4px; }
        .header p { font-size: 12px; color: #666; letter-spacing: 0.1em; text-transform: uppercase; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th { background: #1A1611; color: #C4973B; padding: 10px 14px; font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em; text-align: left; }
        td { padding: 12px 14px; border-bottom: 1px solid #E8E0D4; font-size: 13px; }
        tr:nth-child(even) td { background: #FAFAF7; }
        .hero { color: #8B6914; font-weight: 600; }
        .price { font-weight: 700; }
        .footer { text-align: center; margin-top: 30px; padding-top: 12px; border-top: 1px solid #E0D5C0; font-size: 10px; color: #999; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Line Sheet</h1>
        <p>Complete Product Catalog · ${new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}</p>
      </div>
      <table>
        <thead>
          <tr><th>SKU</th><th>Product</th><th>Category</th><th>Description</th><th>Price</th></tr>
        </thead>
        <tbody>
          ${products.map((p) => `
            <tr class="${p.hero ? "hero" : ""}">
              <td>${p.sku}</td>
              <td>${p.name}${p.hero ? " ★" : ""}</td>
              <td>${p.category}</td>
              <td>${p.description}</td>
              <td class="price">${p.price}</td>
            </tr>
          `).join("")}
        </tbody>
      </table>
      <div class="footer">
        ${products.length} products · Generated by Marie AI · ${new Date().toLocaleDateString()} · Confidential
      </div>
    </body>
    </html>
  `;
}

export function exportPDF({ products, type }: PDFExportProps) {
  const html = type === "sell-sheet" ? generateSellSheet(products) : generateLineSheet(products);

  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to export PDFs.");
    return;
  }

  printWindow.document.write(html);
  printWindow.document.close();

  // Wait for fonts to load then trigger print
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };
}
